using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System.Collections.ObjectModel;
using System.Diagnostics;
using TwinTrack.Models;
using TwinTrack.Services;
using TwinTrack.ViewModels;
using Windows.Storage.Pickers;

namespace TwinTrack;

public sealed partial class MainWindow : Window
{
    private readonly StateStore _store=new(); private readonly ScannerService _scanner=new();
    private readonly ObservableCollection<FolderVm> _folders=new(); private readonly ObservableCollection<TrackRowVm> _rows=new();
    private AppState _state=new(); private ScanResult? _currentResult; private FolderVm? _selected; private Task<ScanResult>? _scanTask; private bool _showingTrash;
    public MainWindow(){InitializeComponent(); FoldersList.ItemsSource=_folders; TracksList.ItemsSource=_rows; Activated+=async(_,_)=>{if(_state.Folders.Count==0&&_folders.Count==0)await LoadInitialAsync();};}
    private async Task LoadInitialAsync(){_state=await _store.LoadAsync(); _folders.Clear(); foreach(var f in _state.Folders)_folders.Add(new FolderVm(f)); TrashCount.Text=_state.Trash.Count.ToString(); if(_folders.Count>0)FoldersList.SelectedIndex=0; else SetEmptyState();}
    private async void AddFolder_Click(object sender,RoutedEventArgs e){var picker=new FolderPicker(); picker.FileTypeFilter.Add("*"); var hwnd=WinRT.Interop.WindowNative.GetWindowHandle(this); WinRT.Interop.InitializeWithWindow.Initialize(picker,hwnd); var folder=await picker.PickSingleFolderAsync(); if(folder==null)return; string path=Path.GetFullPath(folder.Path).TrimEnd(Path.DirectorySeparatorChar); var existing=_folders.FirstOrDefault(x=>string.Equals(Path.GetFullPath(x.Path).TrimEnd(Path.DirectorySeparatorChar),path,StringComparison.OrdinalIgnoreCase)); if(existing!=null){FoldersList.SelectedItem=existing;return;} var model=new FolderModel{Id=Guid.NewGuid().ToString("N"),Name=Path.GetFileName(path),Path=path}; if(string.IsNullOrWhiteSpace(model.Name))model.Name=path; _state.Folders.Add(model); var vm=new FolderVm(model); _folders.Add(vm); await _store.SaveAsync(_state); FoldersList.SelectedItem=vm; _=Task.Run(async()=>{int count=await _scanner.CountAudioAsync(path); DispatcherQueue.TryEnqueue(async()=>{vm.FileCount=count;await _store.SaveAsync(_state);});});}
    private async void RemoveFolder_Click(object sender,RoutedEventArgs e){if(sender is not Button{Tag:FolderVm vm})return; if(_scanner.IsRunning&&_scanner.ActiveFolderId==vm.Id){_scanner.Cancel();if(_scanTask!=null){try{await _scanTask;}catch{}}} _state.Folders.RemoveAll(x=>x.Id==vm.Id);_folders.Remove(vm);await _store.SaveAsync(_state);if(FoldersList.SelectedItem==null&&_folders.Count>0)FoldersList.SelectedIndex=0;if(_folders.Count==0)SetEmptyState();}
    private async void FoldersList_SelectionChanged(object sender,SelectionChangedEventArgs e){if(FoldersList.SelectedItem is not FolderVm vm)return;_showingTrash=false;_selected=vm;await LoadFolderResultAsync(vm);}
    private async Task LoadFolderResultAsync(FolderVm vm){_currentResult=await _store.LoadResultAsync(vm.Id);if(_currentResult==null){_rows.Clear();SummaryText.Text="Нажмите «Сканировать», чтобы найти точные дубли";FilesStat.Text=vm.FileCount.ToString();GroupsStat.Text="0";BytesStat.Text="0 Б";if(!_scanner.IsRunning){StatusText.Text="Готово";Progress.Value=0;ProgressText.Text="0%";}return;} await PopulateRowsAsync(_currentResult.Groups);SummaryText.Text=$"Найдено {_currentResult.Summary.DuplicateCount} точных дублей";FilesStat.Text=_currentResult.FileCount.ToString();GroupsStat.Text=_currentResult.Summary.GroupCount.ToString();BytesStat.Text=TrackRowVm.FormatBytes(_currentResult.Summary.DuplicateBytes);if(!_scanner.IsRunning){StatusText.Text="Сканирование завершено";Progress.Value=100;ProgressText.Text="100%";}}
    private async Task PopulateRowsAsync(IEnumerable<List<FileItem>> groups){var trashPaths=_state.Trash.Select(x=>x.FullPath).ToHashSet(StringComparer.OrdinalIgnoreCase);var flat=groups.SelectMany((g,gi)=>g.Select(x=>(x,gi))).Where(t=>!trashPaths.Contains(t.x.FullPath)).ToList();await Task.Run(()=>{foreach(var t in flat){var meta=MetadataReader.Read(t.x.FullPath);t.x.Artist=meta.Artist;t.x.Title=meta.Title;}});_rows.Clear();foreach(var t in flat)_rows.Add(new TrackRowVm{Item=t.x,GroupIndex=t.gi});}
    private async void Scan_Click(object sender,RoutedEventArgs e){if(_selected==null||_scanner.IsRunning)return;var scanFolder=_selected;ScanButton.IsEnabled=false;PauseButton.IsEnabled=true;PauseLabel.Text="Пауза";PauseGlyph.Glyph="\uE769";var progress=new Progress<ScanProgress>(p=>{Progress.Value=Math.Clamp(p.Percent,0,100);ProgressText.Text=$"{(int)p.Percent}%";StatusText.Text=p.Text;});try{_scanTask=_scanner.ScanAsync(scanFolder.Model,progress);var result=await _scanTask;scanFolder.Model.FileCount=result.FileCount;scanFolder.Model.HasResults=true;scanFolder.Refresh();await _store.SaveResultAsync(result);await _store.SaveAsync(_state);if(_selected?.Id==scanFolder.Id&&!_showingTrash)await LoadFolderResultAsync(scanFolder);}catch(OperationCanceledException){StatusText.Text="Сканирование остановлено";}catch(Exception ex){StatusText.Text="Ошибка: "+ex.Message;}finally{ScanButton.IsEnabled=true;PauseButton.IsEnabled=false;PauseLabel.Text="Пауза";PauseGlyph.Glyph="\uE769";_scanTask=null;}}
    private void Pause_Click(object sender,RoutedEventArgs e){if(!_scanner.IsRunning)return;if(_scanner.IsPaused){_scanner.Resume();PauseLabel.Text="Пауза";PauseGlyph.Glyph="\uE769";StatusText.Text="Продолжение сканирования…";}else{_scanner.Pause();PauseLabel.Text="Продолжить";PauseGlyph.Glyph="\uE768";StatusText.Text="Пауза";}}
    private void ShowFile_Click(object sender,RoutedEventArgs e){if(sender is not Button{Tag:TrackRowVm row})return;try{Process.Start(new ProcessStartInfo("explorer.exe",$"/select,\"{row.FullPath}\""){UseShellExecute=true});}catch{}}
    private async void MoveToTrash_Click(object sender,RoutedEventArgs e){if(sender is not Button{Tag:TrackRowVm row})return;if(_showingTrash){_state.Trash.RemoveAll(x=>string.Equals(x.FullPath,row.FullPath,StringComparison.OrdinalIgnoreCase));await _store.SaveAsync(_state);await ShowTrashAsync();return;}_state.Trash.RemoveAll(x=>string.Equals(x.FullPath,row.FullPath,StringComparison.OrdinalIgnoreCase));_state.Trash.Add(row.Item);await _store.SaveAsync(_state);TrashCount.Text=_state.Trash.Count.ToString();_rows.Remove(row);}
    private async void Trash_Click(object sender,RoutedEventArgs e)=>await ShowTrashAsync();
    private async Task ShowTrashAsync(){_showingTrash=true;_rows.Clear();var items=_state.Trash.ToList();await Task.Run(()=>{foreach(var x in items){var meta=MetadataReader.Read(x.FullPath);x.Artist=meta.Artist;x.Title=meta.Title;}});foreach(var x in items)_rows.Add(new TrackRowVm{Item=x,GroupIndex=0});SummaryText.Text=$"Корзина TWINTRACK · {items.Count}";TrashCount.Text=items.Count.ToString();FilesStat.Text=items.Count.ToString();GroupsStat.Text="—";BytesStat.Text=TrackRowVm.FormatBytes(items.Sum(x=>x.Size));}
    private void Exit_Click(object sender,RoutedEventArgs e)=>Close();
    private void SetEmptyState(){_selected=null;_currentResult=null;_rows.Clear();SummaryText.Text="Добавьте папку с музыкой";FilesStat.Text="0";GroupsStat.Text="0";BytesStat.Text="0 Б";StatusText.Text="Готово";Progress.Value=0;ProgressText.Text="0%";}
}
